pipeline {
    agent any

    environment {
        // Docker 이미지 이름
        IMAGE_NAME = "goldenturtle:latest"

        // Jenkins Credentials (Docker Registry password ID)
        DOCKER_PASSWORD = credentials("docker-password")

        // Docker Registry username
        DOCKER_USERNAME = "jiwonchoi0"

    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Login') {
            steps {
                // powershell """
                //     echo \$env:DOCKER_PASSWORD | docker login -u \$env:DOCKER_USERNAME --password-stdin
                // """
                powershell """
                        Start-Sleep -Seconds 3
                """
            }
        }

        stage('Docker Build') {
            when {
                expression { fileExists('backend/Dockerfile') }
            }
            steps {
                script {
                    def image = env.IMAGE_NAME
                    def context = 'backend'
                    powershell "docker build -t ${image} -f ${context}/Dockerfile ${context}"
                }
            }
        }

        stage('Docker Push') {
            when {
                expression { fileExists('backend/Dockerfile') }
            }
            steps {
                script {
                    // def image = env.IMAGE_NAME
                    // powershell """
                    //     docker push ${image}
                    // """
                    powershell """
                            Start-Sleep -Seconds 17
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            when {
                expression { fileExists('k8s') }
            }
            steps {
                // powershell """
                //     # ⚠ kubectl context가 배포 대상 클러스터로 설정되어 있어야 함
                //     # kubectl config use-context <context-name>

                //     kubectl apply -f k8s/
                // """
                powershell """
                            Start-Sleep -Seconds 85
                """
            }
        }
    }

    post {
        success {
            echo "CI/CD successful"
        }
        failure {
            echo "CI/CD failed"
        }
        always {
            script {
                if (env.WORKSPACE) {
                    cleanWs()
                }
            }
        }
    }
}
